basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a notification system.
  title: Notification System API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Responds with a simple message to check if the server is up and
        running.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Ping the server
      tags:
      - system
swagger: "2.0"
